spring:
  #数据库配置
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/sso?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  #Redis配置
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password:
  #热部署配置
  devtools:
    restart:
      enabled: false
