#项目配置文件
quick:
  # 文件基路径 示例（ Windows配置D:\upload，Linux配置 /home/app/upload）
  file-base-dir: D:\upload
spring:
  #Redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  #数据源
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/quick?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  #热部署配置
  devtools:
    restart:
      enabled: false
#mybatis-plus配置控制台打印完整带参SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#日志
logging:
  file:
    path: logs/
  level:
    root: info
