#项目配置文件
quick:
  # 文件基路径 示例（ Windows配置D:\upload，Linux配置 /home/app/upload）
  file-base-dir: /home/app/upload
spring:
  #Redis配置 , 与单点登录服务同一Redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  #数据源
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/quick?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#生产环境关闭SQL日志输出
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
